APT::FTPArchive::Release::Origin "Solo-it";
APT::FTPArchive::Release::Label "backupctl";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64";
APT::FTPArchive::Release::Components "main";
